trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'github-helper'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: app/Dockerfile